### ISSUE TITLE
Some remarks on the crypto used

### ISSUE THREAD

**Issue by X-Ryl669** [turtl/server#1]
1. The random_token code use a useless hash, with a low complexity salt size and user guessable time that's lowering the entropy of the random source used. Using a hash on a random source does not increase entropy, but hashing a random source with not-so-random data does lower the entropy. There is no need to hash with a large algorithm either, as it'll just slow generation with no benefit.
To me, a `sha256(random(64))` is faster and more secure

**Comment by orthecreedence** [comment]
Thanks, this is great feedback. You're right...not sure what I was thinking here. I'll fix.
